### ISSUE TITLE
Issue with cURL export

### ISSUE THREAD

**Issue by Kirow** [luckymarmot/Paw-cURLCodeGenerator#12]
I have header `'$2y$10$mPVo8WIu3KQFw.LAKl/Lk.LjOP/VWPXIZJcneLagVxFjWg9WV4Dlu'`

extension suggest me export this like:
`     -H "session: $2y$10$mPVo8WIu3KQFw.LAKl/Lk.LjOP/VWPXIZJcneLagVxFjWg9WV4Dlu" `
but it should be:
`    -H "session: \$2y\$10\$mPVo8WIu3KQFw.LAKl/Lk.LjOP/VWPXIZJcneLagVxFjWg9WV4Dlu"`

**Comment by mittsh** [comment]
Sorry for the massive delay @Kirow & @donatj 

Fixed in #14
