### ISSUE TITLE
Set "Accept" header in JSON requests

### ISSUE THREAD

**Issue by jamescoletti** [luckymarmot/Paw-cURLCodeGenerator#4]
When generating cURL commands for JSON requests, the `Content-Type: application/json` header is being set to describe the request data, but the `Accept: application/json` header is not set to explicitly request a JSON response. In JSON-only APIs, this isn't an issue, but we are working with APIs that return various data formats. Without the `Accept` header, many of them default to XML. The issue is when we share the cURL commands, they often end up sending JSON but receiving XML back, which isn't an accurate representation of the transactions we're trying to communicate with the snippets.

For example, when sending JSON data to the Typicode test API, I would expect this cURL command to be generated:

```
curl -X "GET" "https://jsonplaceholder.typicode.com/posts/1" \
    -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -d "{}"
```

Thank you for your work on Paw and this extension.

**Comment by JonathanMontane** [comment]
@jamescoletti, thank you for the report, I'll look into it asap.

**Comment by JonathanMontane** [comment]
@jamescoletti I've looked into your issue, and I fail to reproduce it.

![image](https://cloud.githubusercontent.com/assets/5136989/17545352/e78b565e-5edc-11e6-9c3d-43bfbc326672.png)

Are you expecting the cURL Generator to automatically add an `Accept: application/json` header despite it not being present in the Header section?

**Comment by jamescoletti** [comment]
@JonathanMontane Yes, should have made that more explicit. My reasoning is if the client is explicitly sending JSON data with a JSON `Content-Type` header, it would make sense to explicitly request JSON in return. As I mentioned, this is mostly an issue with multi-format APIs that default to something else without an `Accept`. Not sure how common that is, but seemingly more common than I originally anticipated.

Thoughts?

**Comment by JonathanMontane** [comment]
@jamescoletti I am sorry, but we will not implement this feature as API endpoints should be able to return values in other format than the ones in which a POST data was sent. An example of a perfectly legitimate API would be an svg generator API, that would take a JSON describing the content of the svg, and would return a XML file containing the svg. As we can't infer the intent of an API, we cannot deduce whether the content encoding should match the response encoding.

I suggest that you add the `Accept: application/json` header to your requests in Paw to enforce the endpoints to return JSON content.

Sorry to let you down.

**Comment by jamescoletti** [comment]
@JonathanMontane, no worries. Makes sense. Thanks for the consideration.
